fabric_sales:
  target: dev

  outputs:
    dev:
      type: fabricspark
      method: livy
      authentication: CLI

      endpoint: https://api.fabric.microsoft.com/v1
      workspaceid: <your workspace ID>
      lakehouse: <Your Lakehouse Name>
      lakehouseid: <Your Lakehouse ID>

      schema: dbo
      threads: 4

      spark_config:
        name: fabric_sales
